// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs71qbPreEZvt5EmDWr8deKDcY1cyXWhY',
    appId: '1:713426219548:web:a5b4d0ec98e86e95d4e5d9',
    messagingSenderId: '713426219548',
    projectId: 'rahatakapp',
    authDomain: 'rahatakapp.firebaseapp.com',
    storageBucket: 'rahatakapp.firebasestorage.app',
    measurementId: 'G-3VSLD6FMH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpqqrkQzlEt51mG2s5Z_Oo1BJNgeekGkE',
    appId: '1:713426219548:android:25083a3b65201fb9d4e5d9',
    messagingSenderId: '713426219548',
    projectId: 'rahatakapp',
    storageBucket: 'rahatakapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPjXI5Nw_XwuYf-IhRBoNuf-ljnk0RS-Y',
    appId: '1:713426219548:ios:fd1c58fda8849ae9d4e5d9',
    messagingSenderId: '713426219548',
    projectId: 'rahatakapp',
    storageBucket: 'rahatakapp.firebasestorage.app',
    iosBundleId: 'com.example.rahatakFoodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPjXI5Nw_XwuYf-IhRBoNuf-ljnk0RS-Y',
    appId: '1:713426219548:ios:fd1c58fda8849ae9d4e5d9',
    messagingSenderId: '713426219548',
    projectId: 'rahatakapp',
    storageBucket: 'rahatakapp.firebasestorage.app',
    iosBundleId: 'com.example.rahatakFoodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs71qbPreEZvt5EmDWr8deKDcY1cyXWhY',
    appId: '1:713426219548:web:c751fcfee5588661d4e5d9',
    messagingSenderId: '713426219548',
    projectId: 'rahatakapp',
    authDomain: 'rahatakapp.firebaseapp.com',
    storageBucket: 'rahatakapp.firebasestorage.app',
    measurementId: 'G-VV9NMJY3WD',
  );
}
